name: Github Actions 실행하기

on:
  push:
    branches:
      - main

jobs:
  Manual-Deployment-Job:
    runs-on: ubuntu-latest

    steps:
      - name: Github Repository 소스 가져오기
        uses: actions/checkout@v4

      - name: JDK17 설치
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: application.yml 생성
        run: echo ${{ secrets.APPLICATION_YML }} > ./src/main/resources/application.yml

      - name: 테스트 및 빌드하기
        run: |
          chmod +x gradlew
          ./gradlew clean build

      - name: jar 파일명 변경하기
        run: mv ./build/libs/*SANPSHOT.jar ./app.jars

#      - name: EC2 로 jar 파일 전송하기
#        run:
#
#      - name: SSH 로 EC2 에 접속하기(프로세스 실행)
#        run:
