name: 컨테이너 기반 배포하기

on:
  push:
    branches:
      - main

jobs:
  Container-Based-Deployment-Job:
    runs-on: ubuntu-latest

    steps:
      - name: Github Repository 소스 가져오기
        uses: actions/checkout@v4

      - name: JDK17 설치하기
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: application.yml 생성하기
        run: echo ${{ secrets.APPLICATION_YML }} | base64 --decode > ./src/main/resources/application.yml

      - name: 테스트 및 빌드하기
        run: |
          chmod +x gradlew
          ./gradlew clean build

      - name: AWS ECR 접근하기 위한 AWS credentials 설정하기
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: AWS private ECR 로그인하기
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker 이미지 생성하고 tag 붙이기
        run: |
          docker build -t web-server .
          docker tag web-server ${{ steps.login-ecr.outputs.registry }}/web-server:latest

      - name: Docker 이미지 Push 하기
        run: docker push ${{ steps.login-ecr.outputs.registry }}/web-server:latest

      - name: SSH 로 EC2 에 접속하기(ECR 로부터 이미지 pull 하고 컨테이너 실행)
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script_stop: true
          script: |
            docker stop web-server || true
            docker rm web-server || true
            docker pull ${{ steps.login-ecr.outputs.registry }}/web-server:latest
            docker run ${{ steps.login-ecr.outputs.registry }}/web-server:latest
            docker run -d --name web-server -p 8080:8080 ${{ steps.login-ecr.outputs.registry }}/web-server:latest
            sudo fuser -k -n tcp 8080 || true
            
            
            
            


